# This dockerfile is used for local Docker testing (used by Docker Compose)

# requires Node 16+
FROM node:16

# create app dir
RUN mkdir -p /usr/app/src

# set working dir
WORKDIR /usr/app

# Copy all files over for build
COPY . ./

# Install app deps without amending lock file
RUN yarn install --frozen-lockfile

# set environment 
ENV NODE_ENV docker-dev 

# set port
ENV PORT 5005

# expose port 5000, default for aws ebs for api calls
EXPOSE 5005

# build yarn proj into dist output files
RUN yarn build

# run yarn start on `docker run`
CMD ["yarn", "start"]