const URI_USER_SVC = process.env.URI_USER_SVC || 'http://localhost:8080'

const PREFIX_REGISTER_USER_SVC = '/register'
const PREFIX_LOGIN_USER_SVC = '/login'
const PREFIX_AUTH_USER_SVC = '/check-token'
const PREFIX_VALIDATE_SESSION_SVC = '/validate-session'
const PREFIX_LOGOUT_USER_SVC = '/logout'
const PREFIX_UPDATE_PASSWORD_USER_SVC = '/update'

export const URL_REGISTER_USER_SVC = URI_USER_SVC + PREFIX_REGISTER_USER_SVC
export const URL_LOGIN_USER_SVC = URI_USER_SVC + PREFIX_LOGIN_USER_SVC
export const URL_AUTH_USER_SVC = URI_USER_SVC + PREFIX_AUTH_USER_SVC
export const URL_VALIDATE_SESSION_SVC = URI_USER_SVC + PREFIX_VALIDATE_SESSION_SVC
export const URL_LOGOUT_USER_SVC = URI_USER_SVC + PREFIX_LOGOUT_USER_SVC
export const URL_UPDATE_PASSWORD_USER_SVC = URI_USER_SVC + PREFIX_UPDATE_PASSWORD_USER_SVC
