export const STATUS_CODE_CREATED = 201
export const STATUS_CODE_CONFLICT = 409
export const STATUS_CODE_SUCCESS = 200
export const STATUS_CODE_UNAUTHORIZED= 401
export const PREFIX_COOKIE_TOKEN = 'access_token'
export const COOKIE_INTERVIEW_SESSION = 'interview-session'
export const PREFIX_COOKIE_MESSAGES = 'chat-messages'
export const PREFIX_COOKIE_MESSAGES_COUNT = 'messages-count'
export const MIN_USERNAME_LEN = 6
export const MIN_PASSWORD_LEN = 6
export const USER_SERVICE_NETWORK_ERROR_MESSAGE = "Looks like we have some problem connecting to the user service"