const USER_SERVICE_PROD_URL = "";
const USER_SERVICE_LOCAL_URL = "http://localhost:8080";

const QUESTION_SERVICE_PROD_URL = ""
const QUESTION_SERVICE_LOCAL_URL = "http://localhost:8090"

const FRONTEND_SERVICE_PROD_URL = ""
const FRONTEND_SERVICE_LOCAL_URL = "http://localhost:3000"

const USER_SERVICE_URL = process.env.NODE_ENV == "dev"
  ? USER_SERVICE_LOCAL_URL
  : USER_SERVICE_PROD_URL;

const QUESTION_SERVICE_URL = process.env.NODE_ENV == "dev"
  ? QUESTION_SERVICE_LOCAL_URL
  : QUESTION_SERVICE_PROD_URL;

const FRONTEND_SERVICE_URL = process.env.NODE_ENV == "dev"
  ? FRONTEND_SERVICE_LOCAL_URL
  : FRONTEND_SERVICE_PROD_URL;

export default {
  USER_SERVICE_URL,
  QUESTION_SERVICE_URL,
  FRONTEND_SERVICE_URL,
  FRONTEND_SERVICE_LOCAL_URL,
};
